title: Universal GRAMM
description: Universal GRAph Minor Mapping tool for CGRA and other applications.
theme: just-the-docs

url: https://universalgramm.github.io/

plugins:
  - jekyll-default-layout

aux_links:
  UGRAMM Repository: https://github.com/UniversalGRAMM/UGRAMM

color_scheme: dark

always_show_subnavigation: true

collections_dir: collections

collections:
  UGRAMM:
    output: true
  GRAMM:
    output: true
  Tutorials:
    output: true

just_the_docs:
  collections:
    UGRAMM:
      name: UGRAMM Documentation
      nav_fold: false
    GRAMM:
      name: GRAMM Documentation
      nav_fold: false
    Tutorials:
      name: Tutorials
      nav_fold: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
  
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red