title: Universal GRAMM
description: Universal GRAph Minor Mapping tool for CGRA and other applications.
theme: just-the-docs

url: https://universalgramm.github.io/

plugins:
  - jekyll-default-layout

aux_links:
  Template Repository: https://universalgramm.github.io/
