title: Universal GRAMM
description: Universal GRAph Minor Mapping tool for CGRA and other applications.
theme: just-the-docs

url: https://universalgramm.github.io/

plugins:
  - jekyll-default-layout

aux_links:
  UGRAMM Repository: https://github.com/UniversalGRAMM/UGRAMM

color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red